# Generated by Django 4.2.15 on 2024-09-03 19:47

from django.db import migrations

def create_admin_group(apps, schema_editor):
    User = apps.get_model('crm_app', 'CustomUser')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type = ContentType.objects.get_for_model(User)
    permission = Permission.objects.create(
        codename="can_manage_users",
        name="Can Manage Users",
        content_type=content_type,
    )

    admin_group = Group.objects.create(
        name="admin_group"
    )
    admin_group.permissions.set([permission])

def revert(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    Permission.objects.delete(
        codename="can_manage_users"
    )

    Group.objects.delete(
        name="admin_group",
    )



class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_group)
    ]
